---
kind: pipeline
type: docker
name: candidate-merge

concurrency:
  limit: 1

environment:
  ECR_REGISTRY: 289581841508.dkr.ecr.eu-west-1.amazonaws.com

platform:
  os: linux
  arch: amd64

steps:
  - name: pipeline-info-remote
    image: 289581841508.dkr.ecr.eu-west-1.amazonaws.com/drone-plugin-boom-init:1.1.0

  - name: git-flow
    image: 289581841508.dkr.ecr.eu-west-1.amazonaws.com/drone-plugin-gitwork:develop
    pull: always
    settings:
      manifest_type: xml
      git_user:
        from_secret: git_user
      git_password:
        from_secret: git_password
      ssh_private_key:
        from_secret: git_ssh_key


trigger:
  branch:
    - candidate
  event:    
    - push

node:
  aws: runner-1